'use strict';

// Generated by scripts/prepare-token-assets.js before the renderer is bundled.
// The runtime manifest contains lightweight local SVG paths plus lookup aliases;
// the SVG payloads themselves remain separate files and are loaded only when an
// icon is actually rendered. This keeps startup offline while avoiding a huge
// base64 icon payload in the main/renderer startup parse path.
let manifest = {
  tokens: {}, networks: {}, wallets: {}, exchanges: {},
  aliases: { tokens: {}, networks: {}, wallets: {}, exchanges: {} },
  displayNames: { wallets: {}, exchanges: {} }
};
try {
  manifest = require('./assets/token-icons/manifest.json');
} catch (_) {
  // Keep the empty manifest so a source checkout remains usable before the
  // preparation script runs; npm start/test/dist all run preparation first.
}

const categories = new Set(['tokens', 'networks', 'wallets', 'exchanges']);
const entriesCache = new Map();
const entryCache = new Map();

function normalizeLookup(value) {
  return String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function lookupVariants(value) {
  const normalized = normalizeLookup(value);
  if (!normalized) return [];
  const compact = normalized.replace(/-/g, '');
  return compact && compact !== normalized ? [normalized, compact] : [normalized];
}

function directCandidates(category, value) {
  const raw = String(value || '').trim();
  if (!raw) return [];
  if (category === 'tokens') {
    return [raw.toUpperCase(), ...lookupVariants(raw).map((item) => item.toUpperCase())];
  }
  return [raw, ...lookupVariants(raw)];
}

function match(category, values) {
  if (!categories.has(category)) return null;
  const iconMap = manifest[category] || {};
  const aliasMap = manifest.aliases && manifest.aliases[category] || {};
  const inputs = Array.isArray(values) ? values : [values];

  for (const value of inputs) {
    for (const key of lookupVariants(value)) {
      const canonical = aliasMap[key];
      if (canonical && iconMap[canonical]) {
        return { category, key: canonical, src: iconMap[canonical] };
      }
    }

    for (const candidate of directCandidates(category, value)) {
      if (iconMap[candidate]) return { category, key: candidate, src: iconMap[candidate] };
    }
  }
  return null;
}

function resolve(category, values) {
  const result = match(category, values);
  return result ? result.src : null;
}

function matchFirst(requests) {
  for (const request of requests || []) {
    if (!request) continue;
    const result = match(request.category, request.values);
    if (result) return result;
  }
  return null;
}

function resolveFirst(requests) {
  const result = matchFirst(requests);
  return result ? result.src : null;
}

function humanizeKey(value) {
  return String(value || '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())
    .trim();
}

function makeEntry(category, key, src) {
  const displayNames = manifest.displayNames && manifest.displayNames[category] || {};
  return Object.freeze({
    category,
    key,
    name: String(displayNames[key] || humanizeKey(key)).trim(),
    src
  });
}

function entry(category, key) {
  if (!categories.has(category)) return null;
  const rawKey = String(key || '').trim();
  if (!rawKey) return null;
  const cacheKey = `${category}:${rawKey}`;
  if (entryCache.has(cacheKey)) return entryCache.get(cacheKey);

  const iconMap = manifest[category] || {};
  let matchResult = iconMap[rawKey] ? { category, key: rawKey, src: iconMap[rawKey] } : null;
  if (!matchResult) matchResult = match(category, rawKey);
  const result = matchResult ? makeEntry(category, matchResult.key, matchResult.src) : null;
  entryCache.set(cacheKey, result);
  if (result && result.key !== rawKey) entryCache.set(`${category}:${result.key}`, result);
  return result;
}

function entries(category) {
  if (!categories.has(category)) return [];
  if (entriesCache.has(category)) return entriesCache.get(category);

  const iconMap = manifest[category] || {};
  const list = Object.keys(iconMap)
    .map((key) => {
      const cached = entry(category, key);
      return cached || makeEntry(category, key, iconMap[key]);
    })
    .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
  const frozen = Object.freeze(list);
  entriesCache.set(category, frozen);
  return frozen;
}

function createImage(src, label, className) {
  if (!src) return null;
  const img = document.createElement('img');
  img.className = className || 'web3-brand-image';
  img.src = src;
  img.alt = `${String(label || 'Web3').trim() || 'Web3'} icon`;
  img.draggable = false;
  img.decoding = 'async';
  return img;
}

exports.normalizeLookup = normalizeLookup;
exports.lookupVariants = lookupVariants;
exports.match = match;
exports.resolve = resolve;
exports.matchFirst = matchFirst;
exports.resolveFirst = resolveFirst;
exports.entry = entry;
exports.entries = entries;
exports.createImage = createImage;
exports._manifest = manifest;
exports._test = { categories, entriesCache, entryCache };
