'use strict';

// Generated by scripts/prepare-token-assets.js before the renderer is bundled.
// The manifest contains only local data URLs plus lookup aliases, so resolving
// an icon never performs a network request or reads node_modules at runtime.
let manifest = {
  tokens: {}, networks: {}, wallets: {}, exchanges: {},
  aliases: { tokens: {}, networks: {}, wallets: {}, exchanges: {} },
  displayNames: { wallets: {}, exchanges: {} }
};
try {
  manifest = require('./assets/token-icons/manifest.json');
} catch (_) {
  // Keep the empty manifest so a source checkout remains usable before the
  // preparation script runs; npm start/test/dist all run preparation first.
}

const categories = new Set(['tokens', 'networks', 'wallets', 'exchanges']);

function normalizeLookup(value) {
  return String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function lookupVariants(value) {
  const normalized = normalizeLookup(value);
  if (!normalized) return [];
  const compact = normalized.replace(/-/g, '');
  return compact && compact !== normalized ? [normalized, compact] : [normalized];
}

function directCandidates(category, value) {
  const raw = String(value || '').trim();
  if (!raw) return [];
  if (category === 'tokens') {
    return [raw.toUpperCase(), ...lookupVariants(raw).map((item) => item.toUpperCase())];
  }
  return [raw, ...lookupVariants(raw)];
}

function match(category, values) {
  if (!categories.has(category)) return null;
  const iconMap = manifest[category] || {};
  const aliasMap = manifest.aliases && manifest.aliases[category] || {};
  const inputs = Array.isArray(values) ? values : [values];

  for (const value of inputs) {
    for (const key of lookupVariants(value)) {
      const canonical = aliasMap[key];
      if (canonical && iconMap[canonical]) {
        return { category, key: canonical, src: iconMap[canonical] };
      }
    }

    for (const candidate of directCandidates(category, value)) {
      if (iconMap[candidate]) return { category, key: candidate, src: iconMap[candidate] };
    }
  }
  return null;
}

function resolve(category, values) {
  const result = match(category, values);
  return result ? result.src : null;
}

function matchFirst(requests) {
  for (const request of requests || []) {
    if (!request) continue;
    const result = match(request.category, request.values);
    if (result) return result;
  }
  return null;
}

function resolveFirst(requests) {
  const result = matchFirst(requests);
  return result ? result.src : null;
}

function humanizeKey(value) {
  return String(value || '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase())
    .trim();
}

function entries(category) {
  if (!categories.has(category)) return [];
  const iconMap = manifest[category] || {};
  const displayNames = manifest.displayNames && manifest.displayNames[category] || {};
  return Object.keys(iconMap).map((key) => ({
    category,
    key,
    name: String(displayNames[key] || humanizeKey(key)).trim(),
    src: iconMap[key]
  })).sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
}

function createImage(src, label, className) {
  if (!src) return null;
  const img = document.createElement('img');
  img.className = className || 'web3-brand-image';
  img.src = src;
  img.alt = `${String(label || 'Web3').trim() || 'Web3'} icon`;
  img.draggable = false;
  return img;
}

exports.normalizeLookup = normalizeLookup;
exports.lookupVariants = lookupVariants;
exports.match = match;
exports.resolve = resolve;
exports.matchFirst = matchFirst;
exports.resolveFirst = resolveFirst;
exports.entries = entries;
exports.createImage = createImage;
exports._manifest = manifest;